name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Copia os arquivos do repositório
      uses: actions/checkout@v2

    - name: Instalar o python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # ajuste a versão do Python conforme necessário

    - name: Instalar variaveis de ambiente e dependências
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Executar testes
      run: |
        source venv/bin/activate
        task test
